services:

  redis:
    image: redis:7-alpine
    container_name: swapnil-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    
  mongo:
    image: mongo:6.0
    container_name: swapnil-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: swapnil_nodejs_with_redis
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: 
